//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/wsnApp/FrequencyPacket.msg.
//

#ifndef __INET_FREQUENCYPACKET_M_H
#define __INET_FREQUENCYPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class FrequencyPacket;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/wsnApp/FrequencyPacket.msg:28</tt> by nedtool.
 * <pre>
 * //
 * // Generic application packet
 * //
 * // TODO: rename to ApplicationHeader and remove ByteCountChunk from ApplicationHeaderSerializer
 * class FrequencyPacket extends FieldsChunk
 * {
 *     uint8_t freqChannel;
 * }
 * </pre>
 */
class INET_API FrequencyPacket : public ::inet::FieldsChunk
{
  protected:
    uint8_t freqChannel = 0;

  private:
    void copy(const FrequencyPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FrequencyPacket&);

  public:
    FrequencyPacket();
    FrequencyPacket(const FrequencyPacket& other);
    virtual ~FrequencyPacket();
    FrequencyPacket& operator=(const FrequencyPacket& other);
    virtual FrequencyPacket *dup() const override {return new FrequencyPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint8_t getFreqChannel() const;
    virtual void setFreqChannel(uint8_t freqChannel);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FrequencyPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FrequencyPacket& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_FREQUENCYPACKET_M_H

