//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/wsnApp/WsnPacket.msg.
//

#ifndef __INET_WSNPACKET_M_H
#define __INET_WSNPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class WsnPacket;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/wsnApp/WsnPacket.msg:28</tt> by nedtool.
 * <pre>
 * //
 * // Generic application packet
 * //
 * // TODO: rename to ApplicationHeader and remove ByteCountChunk from ApplicationHeaderSerializer
 * class WsnPacket extends FieldsChunk
 * {
 *     uint32_t sequenceNumber;
 *     double xPosition = 0;
 *     double yPosition = 0;
 * }
 * </pre>
 */
class INET_API WsnPacket : public ::inet::FieldsChunk
{
  protected:
    uint32_t sequenceNumber = 0;
    double xPosition = 0;
    double yPosition = 0;

  private:
    void copy(const WsnPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WsnPacket&);

  public:
    WsnPacket();
    WsnPacket(const WsnPacket& other);
    virtual ~WsnPacket();
    WsnPacket& operator=(const WsnPacket& other);
    virtual WsnPacket *dup() const override {return new WsnPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint32_t getSequenceNumber() const;
    virtual void setSequenceNumber(uint32_t sequenceNumber);
    virtual double getXPosition() const;
    virtual void setXPosition(double xPosition);
    virtual double getYPosition() const;
    virtual void setYPosition(double yPosition);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WsnPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WsnPacket& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_WSNPACKET_M_H

